### PR TITLE
Add Node.js compiler

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by megaxlr** [comment]
This compiler is incomplete. It lacks the header and footer. See the Python and C compilers for examples.

**Comment by Marfjeh** [comment]
We'll merge this when you do what @megaxlr said. after that, we'll be moving the compilers in a separate directory because it's getting messy in this repo.

**Comment by kevzdev** [comment]
It's updated @Marfjeh

**Comment by megaxlr** [comment]
Thanks!

**Pull request merged**
